Gui:
  Title: "MapArt Patenting"

  #States for Button-Settings
  States:
    Active: "&7[&aActivated&7]"
    Unactive: "&7[&cDeactivated&7]"

  #Button-Translations
  Buttons:
    Confirm:
      Display: "&7[&aConfirm&7]"
      Lore:
        - "&7Total costs: &a<costs>"
    Insert:
      Display: "&aInsert MapArt"
      Lore: []
    Craftability:
      Costs: 2000
      Display: "&9Prevent Copy"
      Lore:
        - "<state>"
        - " "
        - "&7Costs: &a<costs>"
    Usability:
      Costs: 1000
      Display: "&9Prevent Usage"
      Lore:
        - "<state>"
        - " "
        - "&7Costs: &a<costs>"
    Exit:
      Display: "&cCancel"
      Lore: []

#The Lore your map will have
MapArt:
  Lore:
    - " "
    - "&8Creator: &a<player>"
    - "&8Copyable: <craft_state>"
    - "&8Usable: <use_state>"
    - " "

#Common used translations
Language:
  no_permission: "&4&l✘ &cYou don't have permission to perform that command"
  no_mapart: "&4&l✘ &cThis is not a filled Map"
  not_allowed: "&4&l✘ &cYou aren't allowed to use this map"
  not_enough_money: "&4&l✘ &cYou don't have enough money"
  inventory_full: "&4&l✘ &cYour inventory was full"
  finish: "&bYou successfully patented your map!"