name: MapArtPatent
version: '${project.version}'
main: net.maksy.mapartpatent.MapArtPatent
api-version: 1.20
authors: [ MaksyKun ]
description: Claim your created MapArts
depend: [Vault]

commands:
  mapart:
    description: Use the PatentGui
    usage: /mapart

permissions:
  mapart.use:
    description: Allow /mapart usage
    default: true
  mapart.reload:
    description: Reload the MapArtPatent Config
    default: op